apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudyeti-grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudyeti-grafana
  template:
    metadata:
      labels:
        app: cloudyeti-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
