apiVersion: v1
kind: Service
metadata:
  name: cloudyeti-flask-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: NodePort
  selector:
    app: cloudyeti-flask
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30301
  type: LoadBalancer
