apiVersion: v1
kind: Service
metadata:
  name: wordpress
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: NodePort
  #type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30301
 
